<?php
    /**
     * Camiloo Limited
     *
     * NOTICE OF LICENSE
     *
     * @category   Camiloo
     * @package    Camiloo_Channelunity
     * @copyright  Copyright (c) 2011 Camiloo Limited (http://www.camiloo.co.uk)
     * @license    http://www.camiloo.co.uk/license.txt
     */
    ?>
<div>
<div style="float:left;width:50%;text-align:left;"><img src="http://my.channelunity.com/culogoformodule.gif" /></div>
<div style="float:left;width:50%;text-align:right;">
<h3>ChannelUnity Integration for Magento</h3>
Devised and Developed in Manchester, UK by <a href="http://www.camiloo.co.uk/?ref=cu" target="_blank">Camiloo Limited</a><br />
<?php 
    $xml = Mage::getModel('channelunity/checkforupdates')->getRemoteXMLFileData("http://my.channelunity.com/versioncheck.php?Version=1.0.0.5");
    $html = $xml->DisplayMessage[0];
    echo $html;
    ?>

</div>
</div>
<div style="clear:both"> &nbsp; </div>   