<?php
 /**
 * ChannelUnity connector for Magento Commerce 
 *
 * @category   Camiloo
 * @package    Camiloo_Channelunity
 * @copyright  Copyright (c) 2011 Camiloo Limited (http://www.camiloo.co.uk)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
//$ii = $this->getMethod()->getInfoInstance()->getData();
    
    /*
 $order = Mage::getModel('sales/order')->load($ii->getData('parent_id'));	
 $remoteOrderId = $ii->getData('channelunity_remoteorderid');
 $remoteChannelName = $ii->getData('channelunity_remotechannelname');
 $remoteUserId = $ii->getData('channelunity_remoteusername');
    
    
    // TODO - not able to extract the data here
    

echo "<b> ChannelUnity Imported Order </b><br />
 Placed On :  $remoteChannelName <br />
 Remote Order ID :  $remoteOrderId <br />";
     
if($remoteUserId != ""){
	echo $this->__("Remote Customer Username").": ".$remoteUserId."<br />";
}
*/
    echo "<b> ChannelUnity Imported Order </b><br/>";
