<?php
 /**
 * ChannelUnity connector for Magento Commerce 
 *
 * @category   Camiloo
 * @package    Camiloo_Channelunity
 * @copyright  Copyright (c) 2011 Camiloo Limited (http://www.camiloo.co.uk)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
 $order = Mage::getModel('sales/order')->load($this->getMethod()->getInfoInstance()->getData('parent_id'));	
 $remoteOrderId = $this->getMethod()->getInfoInstance()->getData('channelunity_remoteorderid');
 $remoteChannelName = $this->getMethod()->getInfoInstance()->getData('channelunity_remotechannelname');
 $remoteUserId = $this->getMethod()->getInfoInstance()->getData('channelunity_remoteusername');


echo "<b>".$this->__("ChannelUnity Imported Order")."</b><br />
".$this->__("Placed On").": ".$remoteChannelName."<br />
".$this->__("Remote Order ID").": ".$remoteOrderId."<br />";

if($remoteUserId != ""){
	echo $this->__("Remote Customer Username").": ".$remoteUserId."<br />";
}